import s3_amg from "../../assets/images/mercedes_sls_amg.png";
import cla from "../../assets/images/mercedes_cla.png";
import amg_g63 from "../../assets/images/mercedes_utilitario.png";
import amg_g63_black from "../../assets/images/mercedes_utilitario_black.png";

import a6 from "../../assets/images/a6.png";
import r8 from "../../assets/images/r8.png";
import a8 from "../../assets/images/a8.png";

import m2coupe from "../../assets/images/m2coupe.png";
import i8 from "../../assets/images/i8.png";
import x6 from "../../assets/images/x6.png";
import M6 from "../../assets/images/bmw.png";

import gt3 from "../../assets/images/911.png";
import cayman from "../../assets/images/cayman.png";
import macan from "../../assets/images/macan.png";

const carsData = [
  {
    id: 1,
    brand: "BMW",
    model: "M2 Coupe",
    pricePerDay: 200, // dólares
    pricePerMonth: 4000, // dólares
    type: "Sedan",
    color: "Blue",
    image: m2coupe,
    engine: "3.0L 6-cylinder turbo",
    horsepower: 405,
    torque: "550 Nm",
    topSpeed: "250 km/h",
    seats: 4,
    transmission: "Automatic",
  },
  {
    id: 2,
    brand: "BMW",
    model: "i8",
    pricePerDay: 250,
    pricePerMonth: 5000,
    type: "Sedan",
    color: "Silver",
    image: i8,
    engine: "1.5L hybrid electric motor",
    horsepower: 369,
    torque: "570 Nm",
    topSpeed: "250 km/h",
    seats: 4,
    transmission: "Automatic",
  },
  {
    id: 3,
    brand: "BMW",
    model: "X6",
    pricePerDay: 220,
    pricePerMonth: 4400,
    type: "Sedan",
    color: "White",
    image: x6,
    engine: "4.4L V8",
    horsepower: 335,
    torque: "700 Nm",
    topSpeed: "235 km/h",
    seats: 5,
    transmission: "Automatic",
  },
  {
    id: 4,
    brand: "BMW",
    model: "M6",
    pricePerDay: 300,
    pricePerMonth: 6000,
    type: "Sedan",
    color: "Black",
    image: M6,
    engine: "4.4L V8",
    horsepower: 425,
    torque: "700 Nm",
    topSpeed: "250 km/h",
    seats: 4,
    transmission: "Automatic",
  },
  {
    id: 5,
    brand: "Audi",
    model: "A6",
    pricePerDay: 180,
    pricePerMonth: 3600,
    type: "Sedan",
    color: "Blue",
    image: a6,
    engine: "2.0L TFSI",
    horsepower: 335,
    torque: "500 Nm",
    topSpeed: "250 km/h",
    seats: 5,
    transmission: "Automatic",
  },
  {
    id: 6,
    brand: "Audi",
    model: "R8",
    pricePerDay: 500,
    pricePerMonth: 10000,
    type: "Sedan",
    color: "Black",
    image: r8,
    engine: "5.2L V10",
    horsepower: 562,
    torque: "560 Nm",
    topSpeed: "330 km/h",
    seats: 2,
    transmission: "Automatic",
  },
  {
    id: 7,
    brand: "Audi",
    model: "A8",
    pricePerDay: 220,
    pricePerMonth: 4400,
    type: "Sedan",
    color: "Black",
    image: a8,
    engine: "3.0L V6",
    horsepower: 335,
    torque: "500 Nm",
    topSpeed: "250 km/h",
    seats: 5,
    transmission: "Automatic",
  },
  {
    id: 8,
    brand: "Mercedes-Benz",
    model: "S3 AMG",
    pricePerDay: 350,
    pricePerMonth: 7000,
    type: "Sedan",
    color: "White",
    image: s3_amg,
    engine: "4.0L V8",
    horsepower: 603,
    torque: "850 Nm",
    topSpeed: "250 km/h",
    seats: 5,
    transmission: "Automatic",
  },
  {
    id: 9,
    brand: "Mercedes-Benz",
    model: "CLA",
    pricePerDay: 160,
    pricePerMonth: 3200,
    type: "Sedan",
    color: "Red",
    image: cla,
    engine: "2.0L Inline-4",
    horsepower: 221,
    torque: "350 Nm",
    topSpeed: "240 km/h",
    seats: 5,
    transmission: "Automatic",
  },
  {
    id: 10,
    brand: "Mercedes-Benz",
    model: "AMG G63",
    pricePerDay: 400,
    pricePerMonth: 8000,
    type: "SUV",
    color: "White",
    image: amg_g63,
    engine: "4.0L V8 biturbo",
    horsepower: 577,
    torque: "850 Nm",
    topSpeed: "240 km/h",
    seats: 5,
    transmission: "Automatic",
  },
  {
    id: 11,
    brand: "Mercedes-Benz",
    model: "AMG G63 ",
    pricePerDay: 450,
    pricePerMonth: 9000,
    type: "SUV",
    color: "Black",
    image: amg_g63_black,
    engine: "4.0L V8 biturbo",
    horsepower: 577,
    torque: "850 Nm",
    topSpeed: "240 km/h",
    seats: 5,
    transmission: "Automatic",
  },
  {
    id: 12,
    brand: "Porsche",
    model: "911 GT3",
    pricePerDay: 550,
    pricePerMonth: 11000,
    type: "Sedan",
    color: "Red",
    image: gt3,
    engine: "4.0L flat-6",
    horsepower: 502,
    torque: "469 Nm",
    topSpeed: "320 km/h",
    seats: 2,
    transmission: "Manual",
  },
  {
    id: 13,
    brand: "Porsche",
    model: "Cayman",
    pricePerDay: 300,
    pricePerMonth: 6000,
    type: "Sedan",
    color: "Blue",
    image: cayman,
    engine: "2.5L flat-4",
    horsepower: 350,
    torque: "420 Nm",
    topSpeed: "290 km/h",
    seats: 2,
    transmission: "Automatic",
  },
  {
    id: 14,
    brand: "Porsche",
    model: "Macan",
    pricePerDay: 250,
    pricePerMonth: 5000,
    type: "Sedan",
    color: "White",
    image: macan,
    engine: "2.0L Inline-4",
    horsepower: 248,
    torque: "370 Nm",
    topSpeed: "230 km/h",
    seats: 5,
    transmission: "Automatic",
  },
];

export default carsData;
